name: OramaCadastroSwift
targets:
  OramaCadastroSwift:
    type: framework
    platform: iOS
    deploymentTarget: "10.0"
    sources: [OramaCadastroSwift]
    info:
      path: ./Info.plist
      version: 1.0.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: Alamofire
